# terminal/color
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'

set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# basic behavior
set -g mouse on
set -g history-limit 50000
set -g escape-time 10
set -g focus-events on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

bind c new-window -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind %
bind \\ split-window -h -c "#{pane_current_path}"

bind & kill-window
bind x kill-pane

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# status line
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left
set -g status-style "bg=default,fg=#abb2bf"

set -g status-left-length 40
set -g status-left "#[fg=#61afef,bold] #S #[fg=#5c6370]│"

set -g window-status-format " #[fg=#5c6370]#I:#W "
set -g window-status-current-format " #[fg=#98c379,bold]#I:#W "

set -g status-right-length 80
set -g status-right "#[fg=#5c6370]│ #[fg=#d19a66]%H:%M #[fg=#5c6370]│ #[fg=#c678dd]#H "

set -g pane-border-style "fg=#1e2127"
set -g pane-active-border-style "fg=#61afef"

set -g message-style "bg=#1e2127,fg=#e6efff"
set -g mode-style "bg=#61afef,fg=#1b1b1b"