## Hyprland entrypoint ##

source = modules/colors.conf
source = modules/monitors.conf
source = modules/env.conf
source = modules/programs.conf
source = modules/autostart.conf
source = modules/decorations.conf
source = modules/animations.conf
source = modules/windowrules.conf
source = modules/workspacerules.conf
source = modules/layout.conf
source = modules/misc.conf
source = modules/input.conf
source = modules/binds.conf
