Theme=graphite-vivid
DarkTheme=graphite-vivid
UseDarkTheme=True
UseAccentColor=False
PerScreenDPI=False
Font="JetBrainsMono Nerd Font 11"
MenuFont="JetBrainsMono Nerd Font 10"
TrayFont="JetBrainsMono Nerd Font 10"
TrayOutlineColor=#11131a
TrayTextColor=#c8ccd0
PreferTextIcon=False
ShowLayoutNameInIcon=True
